#!/bin/bash

docker run --rm -d -p 80:80 -p 443:443 \
    --name nginx-proxy-own \
    -v ${PWD}/certs:/etc/nginx/certs:ro \
    -v ${PWD}/conf/bodySize100M.conf:/etc/nginx/conf.d/bodySize100M.conf  \
    -v /etc/nginx/vhost.d \
    -v /usr/share/nginx/html \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/nginx-proxy
